### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by Billccx** [XunshanMan/MVGFormer#1]
Hi !
Thanks for your work. Do you have any plan to open source the code?

**Comment by Billccx** [comment]
Hello! Five months have passed since you created this project. Do you still have any plan to open source the code? Your work is truly impressive.

**Comment by XunshanMan** [comment]
Hi Billccx,
Thank you very much for your interests in our work. We are organizing our code, data and models and have a plan to release them before CVPR conference in June. Thank you for your patience!
Best,

**Comment by Billccx** [comment]
> Hi Billccx, Thank you very much for your interests in our work. We are organizing our code, data and models and have a plan to release them before CVPR conference in June. Thank you for your patience! Best,

Hi! As CVPR is approaching, I wish you a nice conference experience. Additionally, I would like to inquire if you have prepared to open-source your code?

**Comment by Billccx** [comment]
> Hi Billccx, Thank you very much for your interests in our work. We are organizing our code, data and models and have a plan to release them before CVPR conference in June. Thank you for your patience! Best,

Hello XunshanMan:
    CVPR 2024 has already closed, and I noticed that you have not open-sourced the code. Did you encounter any difficulties in the open-sourcing process? Is there anything I can help with? Looking forward to your reply and thanks in advance.

**Comment by Billccx** [comment]
Hello. Is the open source plan canceled?

**Comment by XunshanMan** [comment]
Hi Billccx, 

Sorry for the late response and thanks for your interest! 
Several deadlines have collided recently. We still have the plan and are already working on it, but we need a little more time. We are trying our best to release it in one week. Please stay tuned. Thank you!

Best,
